// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. SEE SOURCE BELOW. !!
pragma solidity ^0.8.20;

interface IOsmiStaking {
    function stakeFor(address user, uint256 amount) external;
    function setAutoStakeFor(address user, bool v) external;
}